### ISSUE TITLE
cv深度学习的相关练习

### ISSUE THREAD

**Issue by SKBL5694** [CV-xueba/Resources#3]
深度学习的cv课程看了80%，老师讲得非常nice，但有没有动手编程的配套练习呢？比如说VAE啊，GAN之类的一些小demo。或者说有什么进一步学习的指导建议，想学习一些代码之类的。

**Comment by nobodypengium** [comment]
想动手编程的话，经验少点的话，可以从PyTorch入手，比较好上手，可以看看[Python深度学习：基于PyTorch](http://www.feiguyunai.com/index.php/2019/06/13/python-ml-pytorch/)，这本书也有纸质版; 当然[PyTorch的官方文档](https://pytorch.org/docs/stable/index.html)也是非常条理清晰的。练习的话，入门可以看一下[这套代码](https://github.com/eriklindernoren/PyTorch-GAN)，简单的网络不到200行，没有一些乱七八糟比较复杂的功能，比较易于学习。然后了解Pytorch之后，可以看看[CycleGAN的官方PyTorch实现](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix)，是一个比较好的训练测试项目模板。

**Comment by SKBL5694** [comment]
十分感谢
